### ISSUE TITLE
First documentation draft

### ISSUE THREAD

**Issue by mocomacode** [Arquisoft/dede_en3b#1]

**Comment by uo276077** [comment]
Issue #8 has been created as part of this issue

**Comment by nic9las** [comment]
Issue #7  (Section 1.2 and 1.3 of documentation (v1) has been created as part of this issue

**Comment by uo276077** [comment]
Issue #5 (Section 2 of documentation (v1)) has been created as part of this issue

**Comment by gsusag00** [comment]
Issue #18 (Section 4 of documentation (v1)) has been created as part of this issue

**Comment by nic9las** [comment]
The version 0.1 of the documentation has been finished.
