### ISSUE TITLE
Curate repository

### ISSUE THREAD

**Issue by mocomacode** [Arquisoft/dede_en3b#3]
Check the current repository and gain a broad understanding of it
so it can be later explained to the rest of the group.

Pay homage to code from other years.

**Comment by gsusag00** [comment]
[Repo Curation.docx](https://github.com/Arquisoft/dede_en3b/files/8074038/Repo.Curation.docx)
First draft of the information gathering phase. Wanted to make it short and brief without going into much detail with technoligies that I barely knew that would probably arise more doubts than fixes 🖌️

**Comment by gsusag00** [comment]
# Our Repository.
## Folder structure

   ### .github/workflows
   - Folder that contains a yml file. Mainly for code coverage. In our case its for the code coverage.
   - A yml or YAML file is a data serialization language. A high level one.
   ### Docs.
   - The docs folder (as the name implies) contains all the documentation revelant to this project.
   - There is a .adoc file for each part of the documentation. 
   - An .adoc file is a file that follows the arc42 template. Arc42 is a template for  architectural documentation
   - How to deploy. To deploy the documentation (locally or on github pages) you can follow the guide on the 

   ### Restapi.
   - A rest API that uses Express and Node.js (Typescript flavor)
   - A rest API is an API that uses HTTP requests to access and use data. The data is accessed through GET, PUT, POST, DELETE (Basically CRUD).
   - In our API there will be an implementation for GET and POST only. Which is implemented in the api.ts file.
      #### Packages used.
      - express: express a NodeJS framwork to build API endpoints, though it has many more uses. Documentation for [Express](https://expressjs.com/en/4x/api.html).
      - CORS: Cross-Origin Resource Sharing. Allows peitions only from certain domains, in our case the domain would be localhost.
      - express-validator: validates the input of the API calls. 
      - express-prom-bundle and prom-client: middleware to capture the petitions and send statistics to prometheus. Prometheus is an open-source system monitoring.
      - @types packages: types for coding using typescript.
### Webapp
- Here is where most of the code we will be working on will take place. 
- It follows the usual React project structure with a the src and the public folder.
- There is two additional folders which are e2e and loadtextexample.
- E2E: End to (2) End testing. There is two ways to test, vertically, starting from a layer of the application (Persistence layer for example) and ending it at the view, monitoring it all the way throught.
- loadtestexample: to simulate a load in our system by carrying petitions to the web app, it uses [Gatling](https://gatling.io/).

There is more in depth information in the readme.md the packages
